### PR TITLE
Resolve #29 Alumni Housing Status

### LINKED ISSUE #29: Clarify On-Floor Status for Alumni in Bad Standing (5.D.2.E, 4.B.2)
Check one:
- [x] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
5.D.2.E describes that `Any Alumni Member in good standing will maintain their previous On Floor status upon a return to Active membership`. 4.B.2 describes that an alumni in bad standing that pass their vote at House Meeting `is reinstated as an Active Member with Off-Floor status effective immediately`.
The implication between these two sections seems to be that Alumni actually lose all housing status and regain it on return to Active membership, with Alumni in good standing getting On-Floor status if they had it and Alumni with bad standing getting Off-Floor status. However, this is not stated actually anywhere and needs to be discussed, clarified, and rewritten.

### PR DESCRIPTION
**Pull request by Qelxiros**
Check one:
- [x] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):

Alumni now always have a housing status, which will be kept when returning to active membership. When an active member enters alumni membership with good standing, they keep their current housing status. If they enter bad standing, they are automatically assigned Off-Floor status.

### CODE REVIEW

**Comment by rhochgraf21** [comment]
resolves #29

**Review by rhochgraf21 — CHANGES_REQUESTED** [review]
Language looks good. Requesting change to clarify that Alumni have housing status as well.

**Review by rhochgraf21 — COMMENTED** [review]
Some notes:
 - per the Housing Priority Process, Alumni in good standing would now be able to reserve spots on floor / be eligible to live on floor. What are your thoughts on this?
 - the current language is unclear as to what occurs when good-standing Alumni become Active. I would interpret it as that they retain their previous status, but more clarity here could be good.

**Comment by rhochgraf21** [comment]
@Qelxiros

**Review by esoccoli — APPROVED** [review]
lgtm

**Pull request merged**
