### PR TITLE
Update #41 Review Responsibilities of the Social Director

### LINKED ISSUE #41: Review Responsibilities of the Socials Director (5.C.4)
Check one:
- [ ] Semantic Issue: something about the meaning of the text is different
- [ ] Non-semantic Issue: Spelling, grammar, or formatting changes.

Summary of issue:
Talk with current and former Socials Directors about the accuracy of and any suggested changes to the constitutional responsibilities of the role.

### PR DESCRIPTION
**Pull request by Sam-Cordry**
Check one:
- [ ] Semantic Change: something about the meaning of the text is different
- [x] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):
Resolve #41 
Namely, this changes wording found in subsection (c) and combines subsections (c) and (d).

### CODE REVIEW

**Review by mxmeinhold — COMMENTED** [review]
I might read this as a semantic change.
Previously: "manage house's events" and "ensure there's a variety of events"
Now: "manage a variety of house events"

It's small, but the implication this could have is that the social director wasn't previously responsible for all events, just those that were House events, and otherwise just had to ensure events happen. This could be read as the events social ensures happen are also social's to manage

Even not holding that reading, this still takes 2 delineated responsibilities and makes one of them less blatant

**Review by rhochgraf21 — DISMISSED** [review]
Personally, I kind of prefer this as two bullets to the condensed single-bullet.

Is there another phrasing that we like better? 

Otherwise - this might be worth leaving as two bullets imo

**Comment by esoccoli** [comment]
@Sam-Cordry

**Review by esoccoli — APPROVED** [review]
lgtm

**Pull request merged**
