### PR TITLE
Reword 5.D.1.B.1 since it was really long and repeated a lot of the same information.

### PR DESCRIPTION
**Pull request by danisaba**
Check one:
- [ ] Semantic Change: something about the meaning of the text is different
- [x] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):
Deleted a few lines at the end that were just reiteration of information above, general rewording to make the section smaller and get the same point across.

### CODE REVIEW

**Comment by mxmeinhold** [comment]
Might be worth making fully excusing dues explicit? Just to ensure it is always seen as an option

**Comment by danisaba** [comment]
> Might be worth making fully excusing dues explicit? Just to ensure it is always seen as an option

That's a great idea, I was thinking about that but wanted to start with minor changes. Thanks!

**Review by esoccoli — APPROVED** [review]
lgtm

**Comment by IgorPolotai** [comment]
The new change now makes it so that only a due reduction or a time extension can be given, but not both. The old text's final line "Additional time and reduction of dues may both be given to a member in an appropriate situation" suggests that both a due reduction and a time extension can be given at the same time in some circumstances, so this should be added to the new change.

**Review by IgorPolotai — CHANGES_REQUESTED** [review]
Add back language to allow for both a due reduction and a time extension.

**Review by esoccoli — APPROVED** [review]
lgtm

**Comment by IgorPolotai** [comment]
Now that the language is added, I think it's all set.

**Pull request merged**
